name: envy
description: An experimental information visualization framework.
version: 0.1.0
author: Rob Bishop <@robbishop65@gmail.com>
homepage: https://github.com/cooler-king/envy
documentation: https://github.com/cooler-king/envy/wiki
environment:
  sdk: ">=1.24.0 <=2.0.0"
dependencies:
  angular: "^4.0.0"
  browser: "^0.10.0"
  collection: ">=1.14.0"
  quantity: "^0.1.0"
  vector_math: "^2.0.5"
dev_dependencies:
  test: "^0.12.15"
dependency_overrides:
  quantity:
    path: ../quantity/
transformers:
- angular:
    entry_points: example/examples.dart

# Run the code generator on the entire package.
- angular/transform/codegen

- angular/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart

# Make pub serve use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
