name: envy
description: An experimental information visualization framework.
version: 0.1.0
author: Rob Bishop <@robbishop65@gmail.com>
homepage: https://github.com/cooler-king/envy
documentation: https://github.com/cooler-king/envy/wiki
environment:
  sdk: ">=1.12.0 <=2.0.0"
dependencies:
  angular: "^4.0.0-alpha+2"
  browser: "^0.10.0"
  collection: ">=1.14.0"
  quantity: "^0.1.0"
  vector_math: "^2.0.5"
dev_dependencies:
  test: "^0.12.15"
dependency_overrides:
  quantity:
    path: ../quantity/
transformers:
- angular:
    entry_points:
    #- example/annular_section2d/test_annular_section2d.html
    resolved_identifiers:
            BrowserClient: 'package:http/browser_client.dart'