name: envy
description: An experimental information visualization framework.
version: 0.0.5
author: Rob Bishop (cooler-king)
homepage: https://github.com/cooler-king/envy
documentation: https://github.com/cooler-king/envy/wiki
environment:
  sdk: ">=1.12.0 <=2.0.0"
dependencies:
  browser: "^0.10.0"
  collection: "^1.1.3"
  polymer: "^1.0.0-rc.9"
  polymer_elements: "^1.0.0-rc.5"
  quantity: "^0.1.0"
  reflectable: "^0.4.0"
  vector_math: "^1.4.3"
  web_components: "^0.12.0"
dev_dependencies:
  test: "^0.12.4"
transformers:
- web_components:
    entry_points:
    - example/annular_section2d/test_annular_section2d.html
    - example/circle2d/test_circle2d.html
    - example/div_node/test_div_node.html
    - example/geo/test_geo.html
    - example/html_node_population/test_html_node_population.html
    - example/image2d/test_image2d.html
    - example/rect2d/test_rect2d.html
    - example/path2d/test_path2d.html
    - example/star2d/test_star2d.html
    - example/text2d/test_text2d.html
    - example/triangle2d/test_triangle2d.html
- reflectable:
    entry_points:
    - example/annular_section2d/test_annular_section2d.dart
    - example/circle2d/test_circle2d.dart
    - example/div_node/test_div_node.dart
    - example/geo/test_geo.dart
    - example/html_node_population/test_html_node_population.dart
    - example/image2d/test_image2d.dart
    - example/rect2d/test_rect2d.dart
    - example/path2d/test_path2d.dart
    - example/star2d/test_star2d.dart
    - example/text2d/test_text2d.dart
    - example/triangle2d/test_triangle2d.dart