name: envy
description: An experimental information visualization framework.
version: 0.0.3
author: Rob Bishop (cooler-king)
homepage: https://github.com/cooler-king/envy
documentation: https://github.com/cooler-king/envy/wiki
environment:
  sdk: ">=1.12.0 <=2.0.0"
dependencies:
  browser: "^0.10.0"
  collection: "^1.1.3"
  polymer: "1.0.0-rc.2"
  polymer_elements: "1.0.0-rc.2"
  quantity: "^0.1.0"
  reflectable: "^0.3.2"
  vector_math: "^1.4.3"
  web_components: "^0.12.0"
dev_dependencies:
  test: "^0.12.4"
transformers:
- web_components:
    entry_points:
    - test/html/test_annular_section2d.html
    - test/html/test_circle2d.html
    - test/html/test_div_node.html
    - test/html/test_html_node_population.html
    - test/html/test_image2d.html
    - test/html/test_rect2d.html
    - test/html/test_path2d.html
    - test/html/test_star2d.html
    - test/html/test_text2d.html
    - test/html/test_triangle2d.html
- reflectable:
    entry_points:
    - test/html/test_annular_section2d.dart
    - test/html/test_circle2d.dart
    - test/html/test_div_node.dart
    - test/html/test_html_node_population.dart
    - test/html/test_image2d.dart
    - test/html/test_rect2d.dart
    - test/html/test_path2d.dart
    - test/html/test_star2d.dart
    - test/html/test_text2d.dart
    - test/html/test_triangle2d.dart